// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyKa.Api.Data;

#nullable disable

namespace MoneyKa.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530220559_AddPasswordHash")]
    partial class AddPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("MoneyKa.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MoneyKa.Api.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saved")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Target")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4CAF82",
                            Icon = "🌴",
                            Saved = 2500m,
                            Target = 5000m,
                            Title = "შვებულება"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#4A90D9",
                            Icon = "📱",
                            Saved = 1200m,
                            Target = 2000m,
                            Title = "ახალი ტელეფონი"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#E07B54",
                            Icon = "🛡️",
                            Saved = 3000m,
                            Target = 5000m,
                            Title = "საგანგებო ფონდი"
                        });
                });

            modelBuilder.Entity("MoneyKa.Api.Models.PushSub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PushSubs");
                });

            modelBuilder.Entity("MoneyKa.Api.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Billing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NextDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Billing = "monthly",
                            Category = "მუსიკა",
                            Color = "#1DB954",
                            Icon = "🎵",
                            Name = "Spotify",
                            NextDate = "2024-06-15",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Billing = "monthly",
                            Category = "ვიდეო",
                            Color = "#FF0000",
                            Icon = "▶️",
                            Name = "YouTube Premium",
                            NextDate = "2024-06-10",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Billing = "monthly",
                            Category = "ვიდეო",
                            Color = "#E50914",
                            Icon = "🎬",
                            Name = "Netflix",
                            NextDate = "2024-06-24",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Billing = "monthly",
                            Category = "ღრუბელი",
                            Color = "#4A90D9",
                            Icon = "☁️",
                            Name = "iCloud+",
                            NextDate = "2024-06-05",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 5,
                            Active = false,
                            Billing = "monthly",
                            Category = "შემოქმედება",
                            Color = "#FF0000",
                            Icon = "🎨",
                            Name = "Adobe Creative",
                            NextDate = "2024-06-18",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("MoneyKa.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecFreq")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -85m,
                            Category = "food",
                            Date = "2024-05-25",
                            Desc = "სუპერმარკეტი",
                            Recurring = false,
                            Time = "14:30",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 2,
                            Amount = -40m,
                            Category = "transport",
                            Date = "2024-05-25",
                            Desc = "ბენზინი",
                            Recurring = false,
                            Time = "12:10",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 3,
                            Amount = -60m,
                            Category = "entertainment",
                            Date = "2024-05-24",
                            Desc = "რესტორანი",
                            Recurring = false,
                            Time = "20:45",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 4,
                            Amount = -15m,
                            Category = "utilities",
                            Date = "2024-05-24",
                            Desc = "Netflix",
                            RecFreq = "monthly",
                            Recurring = true,
                            Time = "09:15",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2800m,
                            Category = "other",
                            Date = "2024-05-01",
                            Desc = "ხელფასი",
                            RecFreq = "monthly",
                            Recurring = true,
                            Time = "10:00",
                            Type = "income"
                        },
                        new
                        {
                            Id = 6,
                            Amount = -120m,
                            Category = "food",
                            Date = "2024-05-22",
                            Desc = "ბაზრობა",
                            Recurring = false,
                            Time = "11:00",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 7,
                            Amount = -35m,
                            Category = "health",
                            Date = "2024-05-21",
                            Desc = "აფთიაქი",
                            Recurring = false,
                            Time = "16:20",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 8,
                            Amount = -25m,
                            Category = "utilities",
                            Date = "2024-05-20",
                            Desc = "მობილური",
                            RecFreq = "monthly",
                            Recurring = true,
                            Time = "09:00",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 9,
                            Amount = -45m,
                            Category = "education",
                            Date = "2024-05-18",
                            Desc = "ონლაინ კურსი",
                            Recurring = false,
                            Time = "14:00",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 10,
                            Amount = -20m,
                            Category = "transport",
                            Date = "2024-05-17",
                            Desc = "მეტრო ბარათი",
                            Recurring = false,
                            Time = "08:30",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 11,
                            Amount = -8m,
                            Category = "utilities",
                            Date = "2024-05-15",
                            Desc = "Spotify",
                            RecFreq = "monthly",
                            Recurring = true,
                            Time = "09:00",
                            Type = "expense"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 450m,
                            Category = "other",
                            Date = "2024-05-10",
                            Desc = "ფრილანს შემოსავალი",
                            Recurring = false,
                            Time = "15:30",
                            Type = "income"
                        });
                });

            modelBuilder.Entity("MoneyKa.Api.Models.UserPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Plan = "free",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
